my_app_filmotheque:
    resource: "@MyAppFilmothequeBundle/Resources/config/routing.yml"
    prefix:   /

dciss_my_app:
    resource: "@dcissMyAppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
